import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';
import * as values from './lib/validators';

export default defineSchema({
  demoSessions: defineTable({ token: v.string(), userId: v.id('users'), expiresAt: v.number(), createdAt: v.number() }).index('by_token', ['token']).index('by_expiry', ['expiresAt']),
  users: defineTable({ demo: v.optional(v.boolean()), authUserId: v.string(), name: v.string(), email: v.string(), phone: v.optional(v.string()), city: v.string(), role: values.role, accountStatus: values.accountStatus, onboardingCompleted: v.boolean(), notificationEnabled: v.boolean(), hospitalId: v.optional(v.id('hospitals')), createdAt: v.number(), updatedAt: v.number() })
    .index('by_auth_user_id', ['authUserId']).index('by_role', ['role']).index('by_account_status', ['accountStatus']),
  donors: defineTable({ demo: v.optional(v.boolean()), userId: v.id('users'), bloodGroup: values.bloodGroup, city: v.string(), latitude: v.optional(v.number()), longitude: v.optional(v.number()), age: v.number(), lastDonationDate: v.optional(v.number()), neverDonated: v.boolean(), available: v.boolean(), temporaryUnavailableUntil: v.optional(v.number()), selfReportedDeferral: v.boolean(), eligibilityStatus: values.eligibilityStatus, totalDonations: v.number(), notificationEnabled: v.boolean(), updatedAt: v.number() })
    .index('by_user', ['userId']).index('by_blood_group', ['bloodGroup']).index('by_group_available', ['bloodGroup', 'available']).index('by_available', ['available']).index('by_eligibility', ['eligibilityStatus']).index('by_city', ['city']),
  hospitals: defineTable({ demo: v.optional(v.boolean()), name: v.string(), city: v.string(), address: v.string(), latitude: v.number(), longitude: v.number(), contact: v.optional(v.string()), verified: v.boolean(), active: v.boolean(), kind: v.union(v.literal('hospital'), v.literal('bloodBank')), createdAt: v.number(), updatedAt: v.number() })
    .index('by_active_city', ['active', 'city']).index('by_active', ['active']).searchIndex('search_name', { searchField: 'name', filterFields: ['active', 'city'] }),
  bloodRequests: defineTable({ demo: v.optional(v.boolean()), requesterId: v.id('users'), clientRequestId: v.string(), bloodGroup: values.bloodGroup, unitsRequired: v.number(), unitsArranged: v.number(), hospitalId: v.id('hospitals'), latitude: v.number(), longitude: v.number(), requiredBefore: v.number(), urgency: values.urgency, description: v.optional(v.string()), aiSummary: v.optional(v.string()), aiSuggestedUrgency: v.optional(values.urgency), verificationStatus: values.verificationStatus, requestStatus: values.requestStatus, searchRadiusKm: v.number(), escalationStage: v.number(), verifiedBy: v.optional(v.id('users')), rejectionReason: v.optional(v.string()), revision: v.number(), createdAt: v.number(), updatedAt: v.number() })
    .index('by_requester', ['requesterId', 'createdAt']).index('by_status', ['requestStatus', 'requiredBefore']).index('by_verification', ['verificationStatus', 'createdAt']).index('by_urgency', ['urgency']).index('by_hospital', ['hospitalId', 'createdAt']).index('by_hospital_status', ['hospitalId', 'requestStatus', 'createdAt']).index('by_created_at', ['createdAt']).index('by_client_request', ['requesterId', 'clientRequestId']),
  donorResponses: defineTable({ demo: v.optional(v.boolean()), requestId: v.id('bloodRequests'), donorId: v.id('donors'), matchScore: v.number(), distanceKm: v.number(), notificationStage: v.number(), responseStatus: values.responseStatus, notifiedAt: v.number(), responseTime: v.optional(v.number()), donationConfirmed: v.boolean(), donationConfirmedBy: v.optional(v.id('users')), donationConfirmedAt: v.optional(v.number()), confirmedUnits: v.number() })
    .index('by_request', ['requestId']).index('by_donor', ['donorId', 'notifiedAt']).index('by_request_and_donor', ['requestId', 'donorId']).index('by_request_status', ['requestId', 'responseStatus']).index('by_response_status', ['responseStatus']),
  donations: defineTable({ demo: v.optional(v.boolean()), requestId: v.id('bloodRequests'), responseId: v.id('donorResponses'), donorId: v.id('donors'), hospitalId: v.id('hospitals'), units: v.number(), confirmedBy: v.id('users'), donatedAt: v.number() })
    .index('by_response', ['responseId']).index('by_donor', ['donorId', 'donatedAt']).index('by_hospital', ['hospitalId', 'donatedAt']),
  notifications: defineTable({ demo: v.optional(v.boolean()), userId: v.id('users'), requestId: v.optional(v.id('bloodRequests')), type: values.notificationType, title: v.string(), body: v.string(), read: v.boolean(), deepLink: v.optional(v.string()), sentAt: v.number(), deliveryStatus: values.deliveryStatus, eventKey: v.string(), error: v.optional(v.string()) })
    .index('by_user', ['userId', 'sentAt']).index('by_user_and_read', ['userId', 'read', 'sentAt']).index('by_event', ['eventKey']),
  pushDevices: defineTable({ demo: v.optional(v.boolean()), userId: v.id('users'), expoPushToken: v.string(), platform: v.union(v.literal('android'), v.literal('ios')), deviceId: v.optional(v.string()), active: v.boolean(), createdAt: v.number(), lastUsedAt: v.number() })
    .index('by_user', ['userId']).index('by_push_token', ['expoPushToken']),
  pushDeliveries: defineTable({ demo: v.optional(v.boolean()), notificationId: v.id('notifications'), deviceId: v.id('pushDevices'), ticketId: v.optional(v.string()), state: values.deliveryStatus, error: v.optional(v.string()), createdAt: v.number(), checkedAt: v.optional(v.number()) })
    .index('by_notification', ['notificationId']).index('by_state', ['state', 'createdAt']),
  reports: defineTable({ demo: v.optional(v.boolean()), requestId: v.id('bloodRequests'), reporterId: v.id('users'), reason: v.string(), details: v.optional(v.string()), status: v.union(v.literal('Open'), v.literal('Resolved'), v.literal('Dismissed')), resolvedBy: v.optional(v.id('users')), resolution: v.optional(v.string()), createdAt: v.number(), resolvedAt: v.optional(v.number()) })
    .index('by_request', ['requestId']).index('by_status', ['status', 'createdAt']).index('by_reporter_request', ['reporterId', 'requestId']),
  auditLogs: defineTable({ demo: v.optional(v.boolean()), userId: v.optional(v.id('users')), action: v.string(), entityType: v.string(), entityId: v.string(), metadata: v.optional(v.record(v.string(), v.union(v.string(), v.number(), v.boolean()))), createdAt: v.number() })
    .index('by_created_at', ['createdAt']).index('by_entity', ['entityType', 'entityId']),
  platformConfig: defineTable({ demo: v.optional(v.boolean()), key: v.literal('main'), operational: values.operationalPolicy, eligibility: v.optional(values.eligibilityPolicy), updatedBy: v.id('users'), updatedAt: v.number() }).index('by_key', ['key']),
});
