import { useState } from 'react';
import { router } from 'expo-router';
import { ScrollView, Switch, Text, View } from 'react-native';
import { Button, Field } from '@/components/auth/ui';
import { StatusBadge } from '@/components/blood/RequestCard';
import { Action, BloodHeader, BloodScreen, BloodSheet, EmptyState, InfoLine, SectionTitle, Segment, ui } from '@/components/blood/ui';
import { colors } from '@/theme/tokens';
import { dateLabel } from '@/features/donor/DonorHome';
import { StaffFeedback, StaffGate, staffStyles as styles, useStaff, type Hospital, type StaffUser } from './shared';

type Staff = ReturnType<typeof useStaff>;
const sections = [{ key: 'users', label: 'Users' }, { key: 'hospitals', label: 'Hospitals' }, { key: 'reports', label: 'Reports' }, { key: 'audit', label: 'Audit log' }, { key: 'config', label: 'Configuration' }];
export default function AdminWorkspace({ section = 'users' }: { section?: string }) {
  const staff = useStaff();
  if (!staff.snapshot?.user || staff.snapshot.user.role !== 'admin') return <StaffGate loading={staff.loading} user={staff.snapshot?.user} admin />;
  const current = sections.find((item) => item.key === section) ?? sections[0];
  return <BloodScreen><BloodHeader back={() => router.back()} /><Text style={ui.title}>{current.label}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={[styles.row, { paddingVertical: 14 }]}>{sections.map((item) => <Button key={item.key} label={item.label} variant={item.key === current.key ? 'solid' : 'outline'} style={styles.button} onPress={() => router.replace({ pathname: '/staff/[section]', params: { section: item.key } })} />)}</ScrollView><StaffFeedback error={staff.error} feedback={staff.feedback} failed={staff.failed} mode={staff.mode} /><View style={[styles.content, { marginTop: 12 }]}>{current.key === 'users' ? <Users staff={staff} /> : current.key === 'hospitals' ? <Hospitals staff={staff} /> : current.key === 'reports' ? <Reports staff={staff} /> : current.key === 'audit' ? <Audit staff={staff} /> : <Configuration staff={staff} />}</View></BloodScreen>;
}

function Users({ staff }: { staff: Staff }) {
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('all');
  const [editing, setEditing] = useState<StaffUser | null>(null);
  const [role, setRole] = useState('requester');
  const [hospitalId, setHospitalId] = useState('');
  const users = (staff.snapshot?.users ?? []).filter((user) => (filter === 'all' || user.role === filter) && `${user.name} ${user.email} ${user.city}`.toLowerCase().includes(search.toLowerCase()));
  return <><Field label="Search users" icon="search" placeholder="Name, email or city" value={search} onChangeText={setSearch} /><Segment values={[{ key: 'all', label: 'All' }, { key: 'donor', label: 'Donors' }, { key: 'requester', label: 'Requesters' }, { key: 'coordinator', label: 'Staff' }]} selected={filter} onSelect={setFilter} />{users.length ? users.map((user) => { const suspended = (user.accountStatus ?? user.status ?? '').toLowerCase() === 'suspended'; return <View key={user.id} style={styles.card}><View style={styles.row}><Text style={[ui.section, styles.flex]}>{user.name}</Text><StatusBadge label={suspended ? 'Suspended' : 'Active'} positive={!suspended} /></View><Text style={ui.muted}>{user.email}</Text><Text style={ui.body}>{user.city} · {user.role}</Text>{user.bloodGroup ? <Text style={ui.muted}>{user.bloodGroup} · {user.available ? 'Available' : 'Paused'} · {user.totalDonations ?? 0} confirmed donations</Text> : null}<View style={styles.row}><Action label="Edit role" icon="edit-2" disabled={!!staff.busy || user.id === staff.snapshot?.user?.id} onPress={() => { setEditing(user); setRole(user.role); setHospitalId(user.hospitalId ?? ''); }} /><Action label={suspended ? 'Restore account' : 'Suspend account'} icon={suspended ? 'check-circle' : 'slash'} disabled={!!staff.busy || user.id === staff.snapshot?.user?.id} onPress={() => staff.run('setUserStatus', { userId: user.id, status: suspended ? 'Active' : 'Suspended' }, suspended ? 'Account restored.' : 'Account suspended.')} /></View></View>; }) : <EmptyState title="No users found" message="Try another name or role filter." icon="users" />}<BloodSheet visible={!!editing} title="Assign account role" onClose={() => setEditing(null)}><Text style={ui.section}>{editing?.name}</Text><InfoLine>Staff assignment grants protected access. Coordinator accounts must belong to a receiving institution.</InfoLine><Segment values={[{ key: 'requester', label: 'Requester' }, { key: 'donor', label: 'Donor' }]} selected={role} onSelect={setRole} /><Segment values={[{ key: 'coordinator', label: 'Coordinator' }, { key: 'admin', label: 'Admin' }]} selected={role} onSelect={setRole} />{role === 'coordinator' ? <><SectionTitle title="Assigned institution" />{(staff.snapshot?.hospitals ?? []).filter((hospital) => hospital.active).map((hospital) => <Button key={hospital.id} label={hospital.name} variant={hospital.id === hospitalId ? 'solid' : 'outline'} onPress={() => setHospitalId(hospital.id)} style={styles.button} />)}</> : null}<Button label="Save assigned role" disabled={!!staff.busy || (role === 'coordinator' && !hospitalId)} busy={staff.busy === 'setUserRole'} onPress={async () => { if (await staff.run('setUserRole', { userId: editing?.id, role, ...(role === 'coordinator' ? { hospitalId } : {}) }, 'Account role updated.')) setEditing(null); }} />{staff.failed && staff.feedback ? <InfoLine>{staff.feedback}</InfoLine> : null}</BloodSheet></>;
}

const emptyHospital = { name: '', city: '', address: '', latitude: '', longitude: '', contact: '', kind: 'hospital' as 'hospital' | 'bloodBank', verified: false, active: true };
function Hospitals({ staff }: { staff: Staff }) {
  const [search, setSearch] = useState('');
  const [show, setShow] = useState(false);
  const [editing, setEditing] = useState<Hospital | null>(null);
  const [draft, setDraft] = useState(emptyHospital);
  const [validation, setValidation] = useState('');
  const hospitals = (staff.snapshot?.hospitals ?? []).filter((hospital) => `${hospital.name} ${hospital.city}`.toLowerCase().includes(search.toLowerCase()));
  function open(hospital?: Hospital) { setEditing(hospital ?? null); setDraft(hospital ? { ...hospital, latitude: String(hospital.latitude), longitude: String(hospital.longitude), contact: hospital.contact ?? '' } : { ...emptyHospital }); setValidation(''); setShow(true); }
  async function save() {
    const latitude = Number(draft.latitude), longitude = Number(draft.longitude);
    if (!draft.name.trim() || !draft.city.trim() || !draft.address.trim() || !draft.latitude.trim() || !draft.longitude.trim() || !Number.isFinite(latitude) || latitude < -90 || latitude > 90 || !Number.isFinite(longitude) || longitude < -180 || longitude > 180) { setValidation('Complete institution details and enter valid latitude and longitude.'); return; }
    if (await staff.run('saveHospital', { ...(editing ? { id: editing.id } : {}), name: draft.name.trim(), city: draft.city.trim(), address: draft.address.trim(), latitude, longitude, contact: draft.contact.trim(), kind: draft.kind, verified: draft.verified, active: draft.active }, editing ? 'Institution updated.' : 'Institution added.')) setShow(false);
  }
  return <><View style={styles.row}><View style={styles.flex}><Field label="Search institutions" icon="search" value={search} onChangeText={setSearch} placeholder="Hospital or city" /></View><Action label="Add" icon="plus" onPress={() => open()} /></View>{hospitals.length ? hospitals.map((hospital) => <View key={hospital.id} style={styles.card}><View style={styles.row}><Text style={[ui.section, styles.flex]}>{hospital.name}</Text><StatusBadge label={hospital.active ? 'Active' : 'Inactive'} positive={hospital.active} /></View><Text style={ui.body}>{hospital.city} · {hospital.kind === 'bloodBank' ? 'Blood bank' : 'Hospital'}</Text><Text style={ui.muted}>{hospital.address}</Text><StatusBadge label={hospital.verified ? 'Verified institution' : 'Verification pending'} positive={hospital.verified} /><Action label="Edit institution" icon="edit-2" onPress={() => open(hospital)} /></View>) : <EmptyState title="No institutions found" message="Add an institution or adjust your search." icon="map-pin" />}<BloodSheet visible={show} title={editing ? 'Edit institution' : 'Add institution'} onClose={() => setShow(false)}>{(['name', 'city', 'address', 'contact', 'latitude', 'longitude'] as const).map((key) => <Field key={key} label={key === 'contact' ? 'Institution contact' : key.charAt(0).toUpperCase() + key.slice(1)} value={draft[key]} onChangeText={(value) => setDraft((previous) => ({ ...previous, [key]: value }))} keyboardType={key === 'latitude' || key === 'longitude' ? 'numbers-and-punctuation' : key === 'contact' ? 'phone-pad' : 'default'} />)}<Segment values={[{ key: 'hospital', label: 'Hospital' }, { key: 'bloodBank', label: 'Blood bank' }]} selected={draft.kind} onSelect={(kind) => setDraft((previous) => ({ ...previous, kind: kind as 'hospital' | 'bloodBank' }))} />{(['verified', 'active'] as const).map((key) => <View style={styles.row} key={key}><Text style={[ui.body, styles.flex]}>{key === 'verified' ? 'Institution verified' : 'Active institution'}</Text><Switch accessibilityLabel={key === 'verified' ? 'Institution verified' : 'Active institution'} value={draft[key]} onValueChange={(value) => setDraft((previous) => ({ ...previous, [key]: value }))} trackColor={{ true: colors.success, false: colors.divider }} /></View>)}{validation ? <Text style={[ui.body, { color: colors.error }]} accessibilityLiveRegion="polite">{validation}</Text> : null}<Button label="Save institution" busy={staff.busy === 'saveHospital'} onPress={save} />{staff.failed && staff.feedback ? <InfoLine>{staff.feedback}</InfoLine> : null}</BloodSheet></>;
}

function Reports({ staff }: { staff: Staff }) {
  const [filter, setFilter] = useState('Open');
  const [selected, setSelected] = useState('');
  const [resolution, setResolution] = useState('');
  const [validation, setValidation] = useState('');
  const reports = (staff.snapshot?.reports ?? []).filter((report) => filter === 'all' || report.status === filter);
  async function resolve(status: 'Resolved' | 'Dismissed') { if (resolution.trim().length < 10) { setValidation('Add the review outcome in at least 10 characters.'); return; } if (await staff.run('resolveReport', { reportId: selected, status, resolution: resolution.trim() }, 'Report review saved.')) setSelected(''); }
  return <><Segment values={[{ key: 'Open', label: 'Open' }, { key: 'Resolved', label: 'Resolved' }, { key: 'all', label: 'All' }]} selected={filter} onSelect={setFilter} />{reports.length ? reports.map((report) => <View key={report.id} style={styles.card}><View style={styles.row}><Text style={[ui.section, styles.flex]}>{report.reason}</Text><StatusBadge label={report.status} positive={report.status !== 'Open'} /></View>{report.details ? <Text style={ui.body}>{report.details}</Text> : null}<Text style={ui.muted}>{dateLabel(report.createdAt)}</Text>{report.resolution ? <Text style={ui.body}>Review: {report.resolution}</Text> : null}<Action label="Inspect reported request" icon="chevron-right" onPress={() => router.push({ pathname: '/request/[id]', params: { id: report.requestId } })} />{report.status === 'Open' ? <Button label="Review report" style={styles.button} onPress={() => { setSelected(report.id); setResolution(''); setValidation(''); }} /> : null}</View>) : <EmptyState title="No reports here" message="Reports in this status will appear here for review." icon="flag" />}<BloodSheet title="Record report review" visible={!!selected} onClose={() => setSelected('')}><Text style={ui.body}>Describe the findings and any action taken.</Text><Field label="Review resolution" multiline value={resolution} onChangeText={setResolution} error={validation} /><Button label="Resolve report" busy={staff.busy === 'resolveReport'} onPress={() => resolve('Resolved')} /><Button label="Dismiss report" variant="outline" disabled={!!staff.busy} onPress={() => resolve('Dismissed')} />{staff.failed && staff.feedback ? <InfoLine>{staff.feedback}</InfoLine> : null}</BloodSheet></>;
}

function Audit({ staff }: { staff: Staff }) {
  const [search, setSearch] = useState('');
  const logs = [...(staff.snapshot?.auditLogs ?? [])].filter((log) => `${log.action} ${log.entityType} ${log.actorName ?? ''}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.createdAt - a.createdAt);
  return <><Field label="Search audit log" icon="search" value={search} onChangeText={setSearch} placeholder="Action, entity or staff member" /><InfoLine>Verification, collection and administration changes are recorded for accountability.</InfoLine>{logs.length ? logs.map((log) => <View key={log.id} style={styles.card}><Text style={ui.section}>{log.action.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/_/g, ' ')}</Text><Text style={ui.body}>{log.entityType}{log.actorName ? ` · ${log.actorName}` : ''}</Text><Text style={ui.muted}>{dateLabel(log.createdAt)} · {new Intl.DateTimeFormat('en-PK', { hour: '2-digit', minute: '2-digit' }).format(log.createdAt)}</Text></View>) : <EmptyState title="No matching activity" message="Recorded actions will appear here." icon="list" />}</>;
}

function Configuration({ staff }: { staff: Staff }) {
  const config = staff.snapshot?.config;
  const operational = config?.operational ?? {};
  const eligibility = config?.eligibility;
  const [draft, setDraft] = useState<Record<string, string>>(() => Object.fromEntries(Object.entries(operational).filter(([, value]) => typeof value === 'number').map(([key, value]) => [key, String(value)])));
  const [policy, setPolicy] = useState({ minimumAge: eligibility?.minimumAge ? String(eligibility.minimumAge) : '', maximumAge: eligibility?.maximumAge ? String(eligibility.maximumAge) : '', minimumDonationIntervalDays: eligibility?.minimumDonationIntervalDays ? String(eligibility.minimumDonationIntervalDays) : '', reference: String(eligibility?.reference ?? '') });
  const [validation, setValidation] = useState('');
  const fields = [{ key: 'initialRadiusKm', label: 'Initial search radius (km)' }, { key: 'maximumRadiusKm', label: 'Maximum search radius (km)' }, { key: 'radiusStepKm', label: 'Radius expansion (km)' }, { key: 'firstBatchSize', label: 'First donor batch' }, { key: 'laterBatchSize', label: 'Later donor batches' }, { key: 'escalationDelayMs', label: 'Escalation delay (milliseconds)' }, { key: 'criticalDelayMs', label: 'Critical delay (milliseconds)' }, { key: 'maximumStages', label: 'Maximum escalation stages' }];
  async function saveOperational() {
    const values: Record<string, number> = {};
    for (const field of fields) { const value = Number(draft[field.key]); if (!draft[field.key]?.trim() || !Number.isFinite(value) || value <= 0 || (field.key.includes('Batch') || field.key === 'maximumStages') && !Number.isInteger(value)) { setValidation('Enter positive values. Batches and stages must be whole numbers.'); return; } values[field.key] = value; }
    if (values.maximumRadiusKm < values.initialRadiusKm) { setValidation('Maximum radius must be at least the initial radius.'); return; }
    setValidation(''); await staff.run('setConfig', { operational: { ...operational, ...values } }, 'Matching and escalation configuration saved.');
  }
  async function savePolicy() {
    const minimumAge = Number(policy.minimumAge), maximumAge = Number(policy.maximumAge), minimumDonationIntervalDays = Number(policy.minimumDonationIntervalDays);
    if (!policy.reference.trim() || !policy.minimumAge || !policy.maximumAge || !policy.minimumDonationIntervalDays || !Number.isInteger(minimumAge) || !Number.isInteger(maximumAge) || !Number.isInteger(minimumDonationIntervalDays) || minimumAge <= 0 || maximumAge < minimumAge || minimumDonationIntervalDays <= 0) { setValidation('Enter the medically approved age limits, donation interval and policy reference.'); return; }
    setValidation(''); await staff.run('setConfig', { eligibility: { minimumAge, maximumAge, minimumDonationIntervalDays, reference: policy.reference.trim() } }, 'Approved eligibility policy saved.');
  }
  return <><SectionTitle title="Matching & escalation" />{!config ? <InfoLine>Configuration is not available yet. Refresh after connecting the staff workspace.</InfoLine> : null}{fields.map((field) => <View key={field.key} style={{ gap: 5 }}><Text style={ui.muted}>{field.label}</Text><Field label={field.label} value={draft[field.key] ?? ''} onChangeText={(value) => setDraft((previous) => ({ ...previous, [field.key]: value }))} keyboardType="numeric" /></View>)}<Button label="Save matching configuration" busy={staff.busy === 'setConfig'} disabled={!config} onPress={saveOperational} /><SectionTitle title="Medically approved eligibility policy" /><InfoLine>{eligibility ? 'The existing policy is applied to preliminary matching. Medical staff determine final donor eligibility.' : 'No eligibility limits are assumed. Donors remain Needs Review until an approved policy is configured.'}</InfoLine>{([{ key: 'minimumAge', label: 'Minimum approved age' }, { key: 'maximumAge', label: 'Maximum approved age' }, { key: 'minimumDonationIntervalDays', label: 'Minimum interval between donations (days)' }, { key: 'reference', label: 'Approved policy reference' }] as const).map((field) => <View key={field.key} style={{ gap: 5 }}><Text style={ui.muted}>{field.label}</Text><Field label={field.label} value={policy[field.key]} onChangeText={(value) => setPolicy((previous) => ({ ...previous, [field.key]: value }))} keyboardType={field.key === 'reference' ? 'default' : 'numeric'} /></View>)}<Button label="Save approved eligibility policy" variant="outline" busy={staff.busy === 'setConfig'} onPress={savePolicy} />{validation ? <Text style={[ui.body, { color: colors.error }]} accessibilityLiveRegion="polite">{validation}</Text> : null}</>;
}
