import { useState } from 'react';
import { router } from 'expo-router';
import Feather from '@expo/vector-icons/Feather';
import { RefreshControl, ScrollView, Text, View } from 'react-native';
import { Button, Field } from '@/components/auth/ui';
import { RequestCard, StatusBadge } from '@/components/blood/RequestCard';
import { closedRequestStatuses } from '@/components/blood/model';
import { Action, BloodHeader, BloodScreen, BloodSheet, EmptyState, InfoLine, SectionTitle, Segment, ui } from '@/components/blood/ui';
import { colors } from '@/theme/tokens';
import { Metric, StaffFeedback, StaffGate, staffStyles as styles, useStaff, type StaffResponse } from './shared';

export default function StaffHome() {
  const staff = useStaff();
  const { snapshot, loading, error, mode, feedback, failed, busy, run } = staff;
  const [tab, setTab] = useState('pending');
  const [refreshing, setRefreshing] = useState(false);
  const [rejectId, setRejectId] = useState('');
  const [reason, setReason] = useState('');
  const [confirmation, setConfirmation] = useState<StaffResponse | null>(null);
  const [units, setUnits] = useState('1');
  const [formError, setFormError] = useState('');
  const user = snapshot?.user;
  if (!user || !['admin', 'coordinator'].includes(user.role)) return <StaffGate loading={loading} user={user} />;
  const admin = user.role === 'admin';
  const assignedHospital = snapshot?.hospitals.find((hospital) => hospital.id === user.hospitalId);
  const requests = (snapshot?.requests ?? []).filter((request) => admin || !user.hospitalId || request.hospitalId === user.hospitalId);
  const pending = requests.filter((request) => request.requestStatus === 'Pending Verification');
  const active = requests.filter((request) => !closedRequestStatuses.has(request.requestStatus) && request.requestStatus !== 'Pending Verification');
  const fulfilled = requests.filter((request) => ['Fulfilled', 'Completed'].includes(request.requestStatus));
  const listed = tab === 'pending' ? pending : tab === 'active' ? active : requests.filter((request) => closedRequestStatuses.has(request.requestStatus));
  const totalUnits = requests.reduce((sum, request) => sum + request.unitsArranged, 0);
  const accepted = (snapshot?.responses ?? []).filter((response) => response.responseStatus === 'Accepted' && !response.donationConfirmed && response.confirmedUnits === 0 && requests.some((request) => request.id === response.requestId)).sort((a, b) => b.matchScore - a.matchScore);
  async function reload() { setRefreshing(true); try { await staff.refresh(); } finally { setRefreshing(false); } }
  async function reject() {
    if (reason.trim().length < 10) { setFormError('Add a clear reason of at least 10 characters.'); return; }
    if (await run('rejectRequest', { requestId: rejectId, reason: reason.trim() }, 'Request rejected with an audit record.')) { setRejectId(''); setReason(''); }
  }
  async function confirm() {
    const value = Number(units);
    const request = requests.find((item) => item.id === confirmation?.requestId);
    if (!confirmation || !Number.isInteger(value) || value < 1 || !request || value > request.unitsRequired - request.unitsArranged) { setFormError('Enter whole units within the request’s remaining requirement.'); return; }
    if (await run('confirmDonation', { responseId: confirmation.id, units: value }, 'Donation confirmed. Units arranged and donor history have updated.')) setConfirmation(null);
  }
  return <BloodScreen scroll={false}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload} tintColor={colors.primary} />}><BloodHeader city={user.city} /><View style={{ gap: 5 }}><Text style={ui.title}>{admin ? 'Platform overview' : 'Hospital workspace'}</Text><Text style={ui.body}>{assignedHospital?.name ?? (admin ? 'Keep the network moving, safely.' : 'Review, coordinate and confirm.')}</Text></View><StaffFeedback error={error} feedback={feedback} failed={failed} mode={mode} /><View style={styles.metrics}><Metric value={pending.length} label="Awaiting review" /><Metric value={active.length} label="Active requests" /><Metric value={totalUnits} label="Units arranged" /></View>
    {admin ? <View style={styles.card}><SectionTitle title="Administration" /><View style={styles.wrap}>{[{ key: 'users', label: 'Users', icon: 'users' as const }, { key: 'hospitals', label: 'Hospitals', icon: 'map-pin' as const }, { key: 'reports', label: 'Reports', icon: 'flag' as const }, { key: 'audit', label: 'Audit log', icon: 'list' as const }, { key: 'config', label: 'Configuration', icon: 'settings' as const }].map((item) => <Action key={item.key} label={item.label} icon={item.icon} onPress={() => router.push({ pathname: '/staff/[section]', params: { section: item.key } })} style={{ paddingHorizontal: 8 }} />)}</View></View> : null}
    <SectionTitle title="Blood requests" /><Segment values={[{ key: 'pending', label: 'To verify' }, { key: 'active', label: 'Active' }, { key: 'history', label: 'History' }]} selected={tab} onSelect={setTab} />{listed.length ? listed.map((request) => <View key={request.id} style={{ gap: 8 }}><RequestCard request={request} variant="active" onPress={() => router.push({ pathname: '/request/[id]', params: { id: request.id } })} />{request.requestStatus === 'Pending Verification' ? <View style={styles.row}><Button label="Verify request" busy={busy === 'verifyRequest'} disabled={!!busy} style={[styles.button, styles.flex]} onPress={() => run('verifyRequest', { requestId: request.id }, 'Request verified. Compatible donor matching is underway.')} /><Button label="Reject" variant="outline" disabled={!!busy} style={[styles.button, styles.flex]} onPress={() => { setRejectId(request.id); setReason(''); setFormError(''); }} /></View> : null}</View>) : <EmptyState title={tab === 'pending' ? 'All caught up' : 'No requests here'} message={tab === 'pending' ? 'New requests awaiting verification will appear here.' : 'Requests in this status will appear here.'} icon="check-circle" />}
    <SectionTitle title="Accepted donors · ranked" /><InfoLine>Ranking uses compatibility, approximate distance and configured matching weights. Staff confirm the donation after collection.</InfoLine>{accepted.length ? accepted.map((response, index) => { const request = requests.find((item) => item.id === response.requestId); return <View key={response.id} style={styles.card}><View style={styles.row}><Text style={styles.number}>{index + 1}</Text><View style={styles.flex}><Text style={ui.section}>{response.donorName || 'Accepted donor'}{response.bloodGroup ? ` · ${response.bloodGroup}` : ''}</Text><Text style={ui.muted}>{request?.hospitalName} · {request?.bloodGroup} requested</Text></View><StatusBadge label="Accepted" positive /></View><View style={styles.row}><Feather name="map-pin" size={16} color={colors.primary} /><Text style={[ui.muted, styles.flex]}>Approx. {Number(response.distanceKm || 0).toFixed(1)} km · Match score {Math.round(response.matchScore)}</Text></View><Button label="Confirm collected donation" disabled={!!busy || !request || request.unitsArranged >= request.unitsRequired || closedRequestStatuses.has(request.requestStatus)} style={styles.button} onPress={() => { setConfirmation(response); setUnits('1'); setFormError(''); }} /><Action label="Request & coordination details" icon="chevron-right" onPress={() => router.push({ pathname: '/request/[id]', params: { id: response.requestId } })} /></View>; }) : <EmptyState title="Awaiting donor acceptance" message="Accepted donors and their ranking will appear here." icon="users" />}
    <SectionTitle title={admin ? 'Network activity' : 'Hospital activity'} /><View style={styles.metrics}><Metric value={fulfilled.length} label="Fulfilled / complete" /><Metric value={requests.length ? `${Math.round(fulfilled.length / requests.length * 100)}%` : '—'} label="Fulfillment rate" /><Metric value={requests.filter((request) => request.urgency === 'Critical' && !closedRequestStatuses.has(request.requestStatus)).length} label="Critical requests" /></View><View style={styles.card}><Text style={ui.section}>Demand by blood group</Text>{['O-', 'O+', 'A-', 'A+', 'B-', 'B+', 'AB-', 'AB+'].map((group) => { const unitsNeeded = active.filter((request) => request.bloodGroup === group).reduce((sum, request) => sum + Math.max(0, request.unitsRequired - request.unitsArranged), 0); return <View key={group} style={styles.row}><Text style={[ui.body, { width: 45 }]}>{group}</Text><View style={{ flex: 1, height: 8, borderRadius: 4, backgroundColor: colors.divider }}><View style={{ width: `${Math.min(100, unitsNeeded / Math.max(1, ...active.map((request) => request.unitsRequired)) * 100)}%`, height: 8, borderRadius: 4, backgroundColor: colors.primary }} /></View><Text style={ui.muted}>{unitsNeeded} units</Text></View>; })}</View>
  </ScrollView><BloodSheet title="Reject request" visible={!!rejectId} onClose={() => setRejectId('')}><Text style={ui.body}>Explain why this request cannot be verified. The requester will see the reason.</Text><Field label="Rejection reason" multiline value={reason} onChangeText={setReason} error={formError} placeholder="Describe the issue to resolve" /><Button label="Reject with reason" busy={busy === 'rejectRequest'} onPress={reject} />{staff.failed && staff.feedback ? <InfoLine>{staff.feedback}</InfoLine> : null}</BloodSheet><BloodSheet title="Confirm donation" visible={!!confirmation} onClose={() => setConfirmation(null)}><Text style={ui.body}>Confirm only blood units already collected and verified by receiving medical staff.</Text><Text style={ui.section}>{confirmation?.donorName || 'Accepted donor'}</Text><Field label="Collected units" value={units} onChangeText={setUnits} keyboardType="number-pad" error={formError} /><InfoLine>This updates units arranged and creates a confirmed entry in the donor’s history.</InfoLine><Button label="Confirm collected units" busy={busy === 'confirmDonation'} onPress={confirm} />{staff.failed && staff.feedback ? <InfoLine>{staff.feedback}</InfoLine> : null}</BloodSheet></BloodScreen>;
}
